# Generated by Django 2.1.2 on 2018-11-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181116_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='atracao',
            name='local',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='atracao',
            name='nome_responsavel',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
