# Generated by Django 2.1.2 on 2018-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181124_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='local',
            field=models.CharField(default='a', max_length=120),
        ),
    ]
