# Generated by Django 2.1.2 on 2018-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_edicao_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='local',
            field=models.CharField(max_length=120),
        ),
    ]
