# Generated by Django 2.1.2 on 2018-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_modalidade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
