# Generated by Django 2.1.2 on 2018-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181124_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='limite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
